import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>  
          <ul>
            <li>Home</li>
            <li>Blog</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
        </nav>
      <main className={styles.main}>
        
        
          <h1 className={styles.title}>Hunting Coder</h1>
          {/* <p className={styles.description}>
            
            A blog for hunting coders by a hunting coder
          </p> */}

          <div className={styles.blogs}>
            <h2>Popular Blogs</h2>
            <div className={styles.blogItem}>
              <h3>How to Learn Javascript in 2022</h3>
              <p>Javascript is Programming Langauge used to write logic for web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to Learn Javascript in 2022</h3>
              <p>Javascript is Programming Langauge used to write logic for web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to Learn Javascript in 2022</h3>
              <p>Javascript is Programming Langauge used to write logic for web</p>
            </div>
          </div>
          
        

        
      </main>
    </>
  )
}
